Add pre- versions and preId input to version.yml
Decided I might as well go all the way with my version workflow file,
otherwise it becomes much less useful to someone using prerelease
versions.

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -12,14 +12,33 @@ on:
           - patch
           - minor
           - major
+          - prerelease
+          - prepatch
+          - preminor
+          - premajor
+      preId:
+        description: 'Prerelease identifier (required with pre-*)'
+        required: false
+        type: string
 
 jobs:
+  validate:
+    name: Validate workflow inputs
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check prerelease identifier
+      if: ${{ startsWith(github.event.inputs.version, 'pre') && !github.event.inputs.preId }}
+      run: |
+        echo "Error: 'preId' input is required with 'pre-*' version."
+        exit 1
+        
+
   version:
     name: Push ${{ inputs.version }} tag
     runs-on: ubuntu-latest
 
-    # permissions:
-      # contents: write
+    needs: [validate]
 
     steps:
     - name: Checkout branch
@@ -27,16 +46,13 @@ jobs:
       with:
       # see https://github.com/orgs/community/discussions/25617#discussioncomment-3248494
         token: ${{ secrets.RELEASE_TOKEN }}
+        # requires contents: write permission for this repo
+        # used by `git push` at the end
     - uses: actions/setup-node@v4
       with:
         node-version: 22.x
-    # - name: Install dependencies
-      # run: npm ci --ignore-scripts
-    # - name: Post-install scripts
-      # run: npm rebuild && npm run prepare --if-present
-    # - name: Build
-      # run: npm run build
     - name: Configure git user
+      # this step is necessary for `npm version` to succeed
       run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor }}@users.noreply.github.com"
